name = "VanillaPlus"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "058f3476f78dd35e0b858761e7296391ac2e7d98f30eaa722e9bbc2963fd6d09"

[versions]
fabric = "0.17.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21.1"]
